// Languages supported by the per-contact "Reply Language" lock.
// First entry is "Auto" (no lock — value "auto"). Remaining entries
// cover ISO 639-1 plus regional / creole variants commonly used on WhatsApp.

export interface LanguageOption {
  code: string;   // value persisted to DB (lowercase). "auto" means no lock.
  name: string;   // human-readable label shown in UI and used in the prompt
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'auto', name: 'Auto (match contact)' },

  // Major world languages (alphabetical by name)
  { code: 'afrikaans', name: 'Afrikaans' },
  { code: 'albanian', name: 'Albanian' },
  { code: 'amharic', name: 'Amharic' },
  { code: 'arabic', name: 'Arabic' },
  { code: 'armenian', name: 'Armenian' },
  { code: 'assamese', name: 'Assamese' },
  { code: 'aymara', name: 'Aymara' },
  { code: 'azerbaijani', name: 'Azerbaijani' },
  { code: 'bambara', name: 'Bambara' },
  { code: 'basque', name: 'Basque' },
  { code: 'belarusian', name: 'Belarusian' },
  { code: 'bengali', name: 'Bengali' },
  { code: 'bhojpuri', name: 'Bhojpuri' },
  { code: 'bosnian', name: 'Bosnian' },
  { code: 'bulgarian', name: 'Bulgarian' },
  { code: 'burmese', name: 'Burmese' },
  { code: 'cantonese', name: 'Cantonese' },
  { code: 'catalan', name: 'Catalan' },
  { code: 'cebuano', name: 'Cebuano' },
  { code: 'chichewa', name: 'Chichewa' },
  { code: 'chinese-simplified', name: 'Chinese (Simplified)' },
  { code: 'chinese-traditional', name: 'Chinese (Traditional)' },
  { code: 'corsican', name: 'Corsican' },
  { code: 'croatian', name: 'Croatian' },
  { code: 'czech', name: 'Czech' },
  { code: 'danish', name: 'Danish' },
  { code: 'dari', name: 'Dari' },
  { code: 'dhivehi', name: 'Dhivehi' },
  { code: 'dogri', name: 'Dogri' },
  { code: 'dutch', name: 'Dutch' },
  { code: 'english', name: 'English' },
  { code: 'esperanto', name: 'Esperanto' },
  { code: 'estonian', name: 'Estonian' },
  { code: 'ewe', name: 'Ewe' },
  { code: 'fijian', name: 'Fijian' },
  { code: 'filipino', name: 'Filipino (Tagalog)' },
  { code: 'finnish', name: 'Finnish' },
  { code: 'french', name: 'French' },
  { code: 'frisian', name: 'Frisian' },
  { code: 'fula', name: 'Fula (Fulani)' },
  { code: 'galician', name: 'Galician' },
  { code: 'ganda', name: 'Ganda (Luganda)' },
  { code: 'georgian', name: 'Georgian' },
  { code: 'german', name: 'German' },
  { code: 'greek', name: 'Greek' },
  { code: 'guarani', name: 'Guarani' },
  { code: 'gujarati', name: 'Gujarati' },
  { code: 'haitian-creole', name: 'Haitian Creole' },
  { code: 'hausa', name: 'Hausa' },
  { code: 'hawaiian', name: 'Hawaiian' },
  { code: 'hebrew', name: 'Hebrew' },
  { code: 'hindi', name: 'Hindi' },
  { code: 'hmong', name: 'Hmong' },
  { code: 'hungarian', name: 'Hungarian' },
  { code: 'icelandic', name: 'Icelandic' },
  { code: 'igbo', name: 'Igbo' },
  { code: 'ilocano', name: 'Ilocano' },
  { code: 'indonesian', name: 'Indonesian' },
  { code: 'irish', name: 'Irish (Gaeilge)' },
  { code: 'italian', name: 'Italian' },
  { code: 'jamaican-patois', name: 'Jamaican Patois' },
  { code: 'japanese', name: 'Japanese' },
  { code: 'javanese', name: 'Javanese' },
  { code: 'kannada', name: 'Kannada' },
  { code: 'kazakh', name: 'Kazakh' },
  { code: 'khmer', name: 'Khmer' },
  { code: 'kinyarwanda', name: 'Kinyarwanda' },
  { code: 'konkani', name: 'Konkani' },
  { code: 'korean', name: 'Korean' },
  { code: 'krio', name: 'Krio (Sierra Leone)' },
  { code: 'kurdish', name: 'Kurdish (Kurmanji)' },
  { code: 'kurdish-sorani', name: 'Kurdish (Sorani)' },
  { code: 'kyrgyz', name: 'Kyrgyz' },
  { code: 'lao', name: 'Lao' },
  { code: 'latin', name: 'Latin' },
  { code: 'latvian', name: 'Latvian' },
  { code: 'lingala', name: 'Lingala' },
  { code: 'lithuanian', name: 'Lithuanian' },
  { code: 'luo', name: 'Luo' },
  { code: 'luxembourgish', name: 'Luxembourgish' },
  { code: 'macedonian', name: 'Macedonian' },
  { code: 'maithili', name: 'Maithili' },
  { code: 'malagasy', name: 'Malagasy' },
  { code: 'malay', name: 'Malay' },
  { code: 'malayalam', name: 'Malayalam' },
  { code: 'maltese', name: 'Maltese' },
  { code: 'mandarin', name: 'Mandarin Chinese' },
  { code: 'maori', name: 'Maori' },
  { code: 'marathi', name: 'Marathi' },
  { code: 'meiteilon', name: 'Meiteilon (Manipuri)' },
  { code: 'mizo', name: 'Mizo' },
  { code: 'mongolian', name: 'Mongolian' },
  { code: 'naija-pidgin', name: 'Naija Pidgin (Nigerian Pidgin)' },
  { code: 'nepali', name: 'Nepali' },
  { code: 'norwegian', name: 'Norwegian' },
  { code: 'odia', name: 'Odia (Oriya)' },
  { code: 'oromo', name: 'Oromo' },
  { code: 'pashto', name: 'Pashto' },
  { code: 'persian', name: 'Persian (Farsi)' },
  { code: 'polish', name: 'Polish' },
  { code: 'portuguese-brazil', name: 'Portuguese (Brazil)' },
  { code: 'portuguese-portugal', name: 'Portuguese (Portugal)' },
  { code: 'punjabi', name: 'Punjabi' },
  { code: 'quechua', name: 'Quechua' },
  { code: 'romanian', name: 'Romanian' },
  { code: 'russian', name: 'Russian' },
  { code: 'samoan', name: 'Samoan' },
  { code: 'sango', name: 'Sango' },
  { code: 'sanskrit', name: 'Sanskrit' },
  { code: 'scots-gaelic', name: 'Scots Gaelic' },
  { code: 'sepedi', name: 'Sepedi' },
  { code: 'serbian', name: 'Serbian' },
  { code: 'sesotho', name: 'Sesotho' },
  { code: 'shona', name: 'Shona' },
  { code: 'sindhi', name: 'Sindhi' },
  { code: 'sinhala', name: 'Sinhala' },
  { code: 'slovak', name: 'Slovak' },
  { code: 'slovenian', name: 'Slovenian' },
  { code: 'somali', name: 'Somali' },
  { code: 'spanish', name: 'Spanish' },
  { code: 'spanish-latam', name: 'Spanish (Latin America)' },
  { code: 'sundanese', name: 'Sundanese' },
  { code: 'swahili', name: 'Swahili' },
  { code: 'swedish', name: 'Swedish' },
  { code: 'tagalog', name: 'Tagalog' },
  { code: 'tajik', name: 'Tajik' },
  { code: 'tamil', name: 'Tamil' },
  { code: 'tatar', name: 'Tatar' },
  { code: 'telugu', name: 'Telugu' },
  { code: 'thai', name: 'Thai' },
  { code: 'tigrinya', name: 'Tigrinya' },
  { code: 'tsonga', name: 'Tsonga' },
  { code: 'tswana', name: 'Tswana' },
  { code: 'turkish', name: 'Turkish' },
  { code: 'turkmen', name: 'Turkmen' },
  { code: 'twi', name: 'Twi' },
  { code: 'ukrainian', name: 'Ukrainian' },
  { code: 'urdu', name: 'Urdu' },
  { code: 'uyghur', name: 'Uyghur' },
  { code: 'uzbek', name: 'Uzbek' },
  { code: 'venda', name: 'Venda' },
  { code: 'vietnamese', name: 'Vietnamese' },
  { code: 'welsh', name: 'Welsh' },
  { code: 'wolof', name: 'Wolof' },
  { code: 'xhosa', name: 'Xhosa' },
  { code: 'yiddish', name: 'Yiddish' },
  { code: 'yoruba', name: 'Yoruba' },
  { code: 'zulu', name: 'Zulu' },
];

export function getLanguageName(code: string | null | undefined): string {
  if (!code || code === 'auto') return 'Auto (match contact)';
  const found = LANGUAGES.find(l => l.code === code);
  return found?.name || code;
}
