/**
 * Telegram Userbot (GramJS / MTProto) — outbound voice notes
 * ============================================================
 *
 * Lets an admin log into their PERSONAL Telegram account from the bot bridge,
 * send a voice note generated by ElevenLabs to ANY recipient (@username,
 * +phone, numeric ID, t.me link, forwarded contact), then immediately wipe
 * the in-memory session for security.
 *
 * Flow (per user):
 *   /login       → bot asks phone → asks code → asks 2FA (if needed)
 *                  → "✅ Logged in as <name>" → state: ready
 *   /send <to>   → bot asks "paste text" → user pastes → bot generates VN
 *                  via ElevenLabs (raw tags or admin-enhance per existing
 *                  rule) → sends as native voice note (waveform) → wipes
 *                  session → "✅ Sent + logged out"
 *   /cancel      → wipe session, abort any pending awaits
 *
 * Session storage: PURE in-memory Map. Never written to disk or SQLite. The
 * GramJS client is disconnected and the StringSession value discarded after
 * every successful send (per user preference).
 */

import { TelegramClient, Api } from 'telegram';
import { StringSession } from 'telegram/sessions/index.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { v4 as uuid } from 'uuid';
import { execSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMP_DIR = path.join(__dirname, '..', 'data', 'temp');

// Optional debug logger injected by the bridge so admin-panel viewers can see
// the full /login + /send lifecycle (stage transitions, errors, etc.).
let _debugLog = null;
export function setUserbotDebugLogger(fn) { _debugLog = typeof fn === 'function' ? fn : null; }
function dlog(userId, action, details = {}) {
  try { _debugLog?.(userId, `userbot_${action}`, details); } catch {}
  try { console.log(`🔧 [userbot ${userId}] ${action}`, details); } catch {}
}

// ── Per-user state ────────────────────────────────────────────────────────
// userId -> {
//   stage: 'idle'|'awaiting_phone'|'awaiting_code'|'awaiting_2fa'|'ready'|'awaiting_recipient'|'awaiting_text'|'sending',
//   client: TelegramClient | null,
//   session: StringSession | null,
//   chatId: string,         // Telegram chat the bot is talking to
//   pendingResolvers: { phone?, code?, password? }, // GramJS .start() callbacks
//   loginPromise: Promise   // resolves when client.start() completes
//   recipient: string | null, // the parsed /send target
//   timeoutHandle: NodeJS.Timeout | null,
// }
const states = new Map();

function getState(userId) {
  if (!states.has(userId)) {
    states.set(userId, {
      stage: 'idle',
      client: null,
      session: null,
      chatId: null,
      pendingResolvers: {},
      loginPromise: null,
      recipient: null,
      timeoutHandle: null,
    });
  }
  return states.get(userId);
}

/** Hard reset: disconnect client, drop session, clear timers. Idempotent. */
async function wipeSession(userId, reason = 'manual') {
  const s = states.get(userId);
  if (!s) return;
  if (s.timeoutHandle) clearTimeout(s.timeoutHandle);
  if (s.client) {
    try { await s.client.disconnect(); } catch {}
    try { await s.client.destroy?.(); } catch {}
  }
  // Reject any in-flight callbacks so .start() throws and unwinds
  for (const k of Object.keys(s.pendingResolvers)) {
    try { s.pendingResolvers[k]?.reject?.(new Error(`session wiped: ${reason}`)); } catch {}
  }
  states.delete(userId);
  console.log(`🔒 [userbot ${userId}] session wiped (${reason})`);
}

/** Set/refresh a 5-min idle timeout. Auto-wipes if user goes silent. */
function armIdleTimeout(userId) {
  const s = states.get(userId);
  if (!s) return;
  if (s.timeoutHandle) clearTimeout(s.timeoutHandle);
  s.timeoutHandle = setTimeout(() => {
    wipeSession(userId, 'idle_timeout').catch(() => {});
  }, 5 * 60 * 1000);
}

/** Make a Promise that the bot polling loop can resolve when user sends a reply. */
function makeAwait(s, key) {
  return new Promise((resolve, reject) => {
    s.pendingResolvers[key] = { resolve, reject };
  });
}

// ── Public API ────────────────────────────────────────────────────────────

/** Returns true if userbot is currently in any non-idle stage for this user. */
export function isBusy(userId) {
  const s = states.get(userId);
  return !!(s && s.stage !== 'idle');
}

/** Get current stage label for status display. */
export function getStage(userId) {
  return states.get(userId)?.stage || 'idle';
}

/**
 * Begin /login flow. Returns immediately; bot prompts user step-by-step.
 * Caller (polling loop) supplies `sendBotMessage(text)` to talk back to user.
 */
export async function startLogin(userId, chatId, sendBotMessage, creds = null) {
  // Per-user creds (saved from Settings) take priority over global env-secret
  // fallback. Either form is accepted so admins can self-serve without ever
  // touching server env vars.
  const apiId = parseInt(
    String(creds?.apiId ?? process.env.TELEGRAM_API_ID ?? ''), 10
  );
  const apiHash = String(creds?.apiHash ?? process.env.TELEGRAM_API_HASH ?? '');
  if (!apiId || !apiHash) {
    await sendBotMessage('⚠️ Userbot not configured. Add your Telegram API ID and API Hash in Settings → Telegram Userbot, or set the TELEGRAM_API_ID / TELEGRAM_API_HASH environment secrets.');
    return;
  }

  // If already mid-flow, refuse politely
  const existing = states.get(userId);
  if (existing && existing.stage !== 'idle') {
    await sendBotMessage(`⚠️ Already in stage "${existing.stage}". Send /cancel to abort first.`);
    return;
  }

  const session = new StringSession('');
  const client = new TelegramClient(session, apiId, apiHash, {
    connectionRetries: 3,
    autoReconnect: false,
    deviceModel: 'Messages Bridge',
    systemVersion: 'Linux',
    appVersion: '1.0.0',
  });

  const s = getState(userId);
  s.stage = 'awaiting_phone';
  s.client = client;
  s.session = session;
  s.chatId = chatId;

  await sendBotMessage('📱 Send your phone number with country code (e.g. +14155551234):');
  armIdleTimeout(userId);

  // Kick off GramJS login — its callbacks await our pendingResolvers which
  // are filled in by the polling loop when the user replies in Telegram.
  s.loginPromise = client.start({
    phoneNumber: async () => {
      const v = await makeAwait(s, 'phone');
      s.stage = 'awaiting_code';
      await sendBotMessage('💬 Enter the login code Telegram just sent you (digits only):');
      armIdleTimeout(userId);
      return v;
    },
    phoneCode: async () => {
      const v = await makeAwait(s, 'code');
      // Note: GramJS may invoke phoneCode multiple times if first attempt
      // was wrong; our Promise model handles only one attempt then aborts.
      return v;
    },
    password: async () => {
      s.stage = 'awaiting_2fa';
      await sendBotMessage('🔐 2FA enabled. Enter your two-step verification password:');
      armIdleTimeout(userId);
      const v = await makeAwait(s, 'password');
      return v;
    },
    onError: async (err) => {
      console.error(`[userbot ${userId}] login error:`, err?.message);
      await sendBotMessage(`⚠️ Login failed: ${err?.message || 'unknown error'}`);
      await wipeSession(userId, 'login_error');
    },
  }).then(async () => {
    // Logged in — confirm identity and move to ready
    try {
      const me = await client.getMe();
      const name = [me.firstName, me.lastName].filter(Boolean).join(' ') || me.username || me.phone || 'unknown';
      s.stage = 'ready';
      armIdleTimeout(userId);
      await sendBotMessage(
        `✅ Logged in as *${escapeMd(name)}*${me.username ? ` (@${escapeMd(me.username)})` : ''}\\.\n\n` +
        `Now send: \`/send <@username|+phone|id|t.me/user>\`\n` +
        `_Session auto\\-wipes after one VN send or 5 min idle\\._`
      );
    } catch (err) {
      await sendBotMessage(`⚠️ Logged in but couldn't fetch identity: ${err?.message}`);
      await wipeSession(userId, 'getme_failed');
    }
  }).catch(async (err) => {
    if (err?.message?.includes('session wiped')) return; // expected on /cancel
    console.error(`[userbot ${userId}] login chain failed:`, err?.message);
    await sendBotMessage(`⚠️ Login failed: ${err?.message || 'unknown error'}`);
    await wipeSession(userId, 'login_chain_error').catch(() => {});
  });
}

/**
 * Route a user-typed reply (non-command text) to whichever pending resolver
 * matches the current stage. Returns true if the message was consumed.
 */
export function feedUserReply(userId, text) {
  const s = states.get(userId);
  if (!s) return false;
  const trimmed = (text || '').trim();
  if (!trimmed) return false;

  if (s.stage === 'awaiting_phone' && s.pendingResolvers.phone) {
    s.pendingResolvers.phone.resolve(trimmed);
    delete s.pendingResolvers.phone;
    return true;
  }
  if (s.stage === 'awaiting_code' && s.pendingResolvers.code) {
    s.pendingResolvers.code.resolve(trimmed.replace(/\s+/g, ''));
    delete s.pendingResolvers.code;
    return true;
  }
  if (s.stage === 'awaiting_2fa' && s.pendingResolvers.password) {
    s.pendingResolvers.password.resolve(trimmed);
    delete s.pendingResolvers.password;
    return true;
  }
  if (s.stage === 'awaiting_text' && s.pendingResolvers.text) {
    s.pendingResolvers.text.resolve(text); // preserve formatting/tags
    delete s.pendingResolvers.text;
    return true;
  }
  return false;
}

/**
 * Begin /send flow. The recipient string is parsed and the user is asked to
 * paste the text body. After text is received, we generate the VN externally
 * via the supplied generator callback and send it through the userbot.
 *
 * `sendVnGenerator(text)` must return Buffer of OGG/Opus audio.
 */
export async function startSend(userId, recipientRaw, sendBotMessage, sendVnGenerator) {
  const s = states.get(userId);
  if (!s || s.stage !== 'ready') {
    await sendBotMessage('⚠️ Not logged in. Send /login first.');
    return;
  }
  if (!recipientRaw?.trim()) {
    await sendBotMessage('⚠️ Usage: `/send <@username|+phone|id|t.me/user>`');
    return;
  }

  // Resolve the recipient via MTProto. GramJS getEntity accepts most formats
  // natively (@username, phone string, numeric ID, t.me link).
  s.stage = 'sending';
  await sendBotMessage(`🔍 Resolving recipient \`${escapeMd(recipientRaw)}\`\\.\\.\\.`);
  let entity;
  try {
    const cleaned = parseRecipient(recipientRaw);
    entity = await s.client.getEntity(cleaned);
  } catch (err) {
    await sendBotMessage(`⚠️ Could not resolve recipient: ${err?.message || 'unknown'}\n_Tip: phone numbers only work if you have them in your Telegram contacts._`);
    s.stage = 'ready';
    armIdleTimeout(userId);
    return;
  }

  s.recipient = entity;
  s.stage = 'awaiting_text';
  const displayName = [entity.firstName, entity.lastName].filter(Boolean).join(' ') ||
                      entity.username || entity.title || String(entity.id);
  await sendBotMessage(
    `🎯 Recipient: *${escapeMd(displayName)}*\n\n` +
    `📝 Now paste the text \\(with or without v3 tags like \`[whisper]\`\\):`
  );
  armIdleTimeout(userId);

  // Wait for the text body
  let text;
  try {
    text = await makeAwait(s, 'text');
  } catch {
    return; // wiped
  }

  if (!text?.trim()) {
    await sendBotMessage('⚠️ Empty text — cancelled.');
    await wipeSession(userId, 'empty_text');
    return;
  }

  s.stage = 'sending';
  await sendBotMessage('🎤 Generating voice note\\.\\.\\.');

  let audioBuffer;
  try {
    audioBuffer = await sendVnGenerator(text);
  } catch (err) {
    await sendBotMessage(`⚠️ VN generation failed: ${err?.message || 'unknown'}`);
    await wipeSession(userId, 'gen_failed');
    return;
  }

  // Persist to a temp .ogg so GramJS can probe duration via ffprobe
  if (!fs.existsSync(TEMP_DIR)) fs.mkdirSync(TEMP_DIR, { recursive: true });
  const oggPath = path.join(TEMP_DIR, `userbot-${uuid()}.ogg`);
  fs.writeFileSync(oggPath, audioBuffer);

  // Compute duration + waveform via ffprobe (best-effort)
  let durationSec = 0;
  try {
    const out = execSync(
      `ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${oggPath}"`,
      { stdio: ['ignore', 'pipe', 'ignore'], timeout: 10000 }
    ).toString().trim();
    durationSec = Math.max(1, Math.round(parseFloat(out) || 1));
  } catch {}

  try {
    await s.client.sendFile(entity, {
      file: oggPath,
      voiceNote: true,
      attributes: [
        new Api.DocumentAttributeAudio({
          duration: durationSec,
          voice: true,
        }),
      ],
    });
    await sendBotMessage(`✅ Voice note sent to *${escapeMd(displayName)}*\\.\n_Logging out\\.\\.\\._`);
  } catch (err) {
    await sendBotMessage(`⚠️ Telegram send failed: ${err?.message || 'unknown'}`);
  } finally {
    try { fs.unlinkSync(oggPath); } catch {}
    await wipeSession(userId, 'send_complete');
  }
}

/** /cancel — abort any in-flight stage and wipe session. */
export async function cancelFlow(userId, sendBotMessage) {
  const s = states.get(userId);
  if (!s || s.stage === 'idle') {
    await sendBotMessage('Nothing to cancel.');
    return;
  }
  await wipeSession(userId, 'user_cancel');
  await sendBotMessage('🛑 Cancelled and session wiped.');
}

// ── Helpers ───────────────────────────────────────────────────────────────

function parseRecipient(raw) {
  let r = raw.trim();
  // t.me link → @username
  const tme = r.match(/t\.me\/([A-Za-z0-9_]+)/i);
  if (tme) return tme[1].startsWith('@') ? tme[1] : '@' + tme[1];
  // Phone: +1234567890
  if (/^\+\d{6,15}$/.test(r)) return r;
  // Numeric ID
  if (/^-?\d{5,}$/.test(r)) return parseInt(r, 10);
  // @username (or bare username — add @)
  if (/^[A-Za-z0-9_]{4,}$/.test(r)) return '@' + r;
  return r; // let GramJS try
}

function escapeMd(text) {
  if (!text) return '';
  return String(text).replace(/([_*\[\]()~`>#+\-=|{}.!\\])/g, '\\$1');
}
